### ISSUE TITLE
Random Crashes.

### ISSUE THREAD

**Issue by jcmejia** [Joseph14078/SRB2#11]
Just randomly crashes after awhile.

**Comment by heyjoeway** [comment]
How are you running the game? Are you starting it from the album applet?

**Comment by jcmejia** [comment]
Yes

**Comment by heyjoeway** [comment]
Read the README:

> NOTE: This game requires full RAM access. This means you can't launch hbmenu from the album applet when running this. With the latest Atmosphere build and its default config, you can hold R while starting any game to open hbmenu with full RAM access.
